name: "The Great Link"
'on':
  workflow_dispatch:
  schedule:
    - cron: 7 2 * * *
jobs:
  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'adopt'
      - uses: extractions/setup-just@v2
      - name: Generate Linked Image
        run: just generate
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'adopt'
      - uses: extractions/setup-just@v2
      - name: Generate Linked Image
        run: just generate
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'adopt'
      - uses: extractions/setup-just@v2
      - name: Get all Dependencies
        run:
          ./mvnw.cmd dependency:copy-dependencies
      - name: Generate List of Module Names
        run:
          java -p target/dependency --add-modules ALL-MODULE-PATH scripts/GetModules.java modnames.txt
      - name: Generate Linked Image
        run:
          jlink --output target/generate --module-path target/dependency --add-modules "@modnames.txt" --bind-services --launcher update4j=org.update4j/org.update4j.Bootstrap
  make_release:
    runs-on: ubuntu-latest
    needs: [ build_macos, build_linux, build_windows ]
    steps:
      - run:
          echo "Hello, world"
