name: "The Great Link"
'on':
  push:
    tags:
      - v*
jobs:
  build_macos:
    runs-on: macos-latest
    steps:
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'adopt'
      - uses: extractions/setup-just@v2
      - name: Generate Linked Image
        run: just generate
      - uses: actions/upload-artifact@v4
        with:
          name:
            the-great-link-macos
          path:
            target/generate
          overwrite:
            true
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'adopt'
      - uses: extractions/setup-just@v2
      - name: Generate Linked Image
        run: just generate
      - uses: actions/upload-artifact@v4
        with:
          name:
            the-great-link-ubuntu
          path:
            target/generate
          overwrite:
            true
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'adopt'
      - uses: extractions/setup-just@v2
      - name: Get all Dependencies
        run:
          ./mvnw.cmd dependency:copy-dependencies
      - name: Generate List of Module Names
        run:
          java -p target/dependency --add-modules ALL-MODULE-PATH scripts/GetModules.java modnames.txt
      - name: Generate Linked Image
        run:
          jlink --output target/generate --module-path target/dependency --add-modules "@modnames.txt" --bind-services --launcher update4j=org.update4j/org.update4j.Bootstrap --launcher jarviz=org.kordamp.jarviz.cli/org.kordamp.jarviz.cli.Main --launcher jstage=dev.mccue.jstage/dev.mccue.jstage.JStage
      - uses: actions/upload-artifact@v4
        with:
          name:
            the-great-link-windows
          path:
            target/generate
          overwrite:
            true
  make_release:
    runs-on: ubuntu-latest
    needs: [ build_macos, build_ubuntu, build_windows ]
    steps:
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: the-great-link-macos
          path: the-great-link-macos
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: the-great-link-ubuntu
          path:
            the-great-link-ubuntu
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: the-great-link-windows
          path:
            the-great-link-windows
      - name: Echo current date
        run: echo $NOW
      - name: List Files
        run:
          tree
      - name: Compress action step
        uses: a7ul/tar-action@v1.1.0
        id: compress
        with:
          command: c
          files: |
            ./the-great-link-macos
          outPath: the-great-link-macos.tar.gz
      - name: Compress action step
        uses: a7ul/tar-action@v1.1.0
        id: compress
        with:
          command: c
          files: |
            ./the-great-link-ubuntu
          outPath: the-great-link-ubuntu.tar.gz
      - uses: vimtor/action-zip@v1.2
        with:
          files: the-great-link-windows
          dest: the-great-link-windows.zip
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.NOW }}
          files: |
            the-great-link-macos.tar.gz
            the-great-link-ubuntu.tar.gz
            the-great-link-windows.zip